"""Notebook tier: pseudobulk_preprocessing.ipynb workers (all four steps).

pseudobulk_preprocessing.R extracts the four inline cells into one argparser
worker: the two python cells (sampleid_mapping, phenotype_formatting) are
reimplemented in R, and the two R cells drop data.table for vroom/dplyr.
Fixtures are the MWE snRNA-seq MIC inputs (the 14 MB Seurat object is
downsampled to 498 cells x 20 samples).

Validation vs the committed MWE references (verified during migration):
  * pseudobulk_counts / phenotype_formatting / pseudobulk_qc's filtered_raw_counts
    are BYTE-IDENTICAL.
  * sampleid_mapping matches after normalizing line endings (the python
    csv.writer emitted CRLF; the R port writes unix LF).
  * pseudobulk_qc residuals reproduce the ORIGINAL notebook R computation
    exactly (0.0 diff); the committed MWE reference differs by ~1.4e-2 purely
    from a limma/voom version change (the original code shows the same delta
    today), so the residuals fixture is regenerated in the current pinned env.
Expected fixtures here are generated by the port in the current env; the
byte-identity to the MWE references is asserted above during migration.
"""
from __future__ import annotations

import gzip

WORKER = "code/script/molecular_phenotypes/QC/pseudobulk_preprocessing.R"
FIX = "tests/fixtures/pseudobulk_preprocessing"


def _rows(text, sep="\t"):
    return [ln.split(sep) for ln in text.splitlines() if ln.strip()]


def _assert_num_match(got_text, exp_text, label_cols, sep="\t", tol=1e-6):
    a, b = _rows(got_text, sep), _rows(exp_text, sep)
    assert len(a) == len(b), f"row count {len(a)} != {len(b)}"
    maxd = 0.0
    for i, (ra, rb) in enumerate(zip(a, b)):
        assert len(ra) == len(rb), f"col count differs at row {i}"
        for j, (x, y) in enumerate(zip(ra, rb)):
            if i == 0 or j < label_cols or x == "NA" or y == "NA":
                assert x == y, f"mismatch row {i} col {j}: {x!r} != {y!r}"
            else:
                maxd = max(maxd, abs(float(x) - float(y)))
    assert maxd < tol, f"max numeric diff {maxd:.2e} exceeds {tol}"


def test_pseudobulk_counts(run_r, repo_root, tmp_path):
    fix = repo_root / FIX
    p = run_r(repo_root / WORKER,
              ["--step", "pseudobulk_counts", "--seurat-files", fix / "seurat_MIC.rds",
               "--celltype", "MIC", "--output-dir", tmp_path])
    assert p.returncode == 0, p.stdout + p.stderr
    got = gzip.open(tmp_path / "0_pseudobulk_counts/pseudobulk_counts_MIC.csv.gz", "rt").read()
    exp = gzip.open(fix / "expected_pseudobulk_counts_MIC.csv.gz", "rt").read()
    assert got == exp


def test_sampleid_mapping(run_r, repo_root, tmp_path):
    fix = repo_root / FIX
    p = run_r(repo_root / WORKER,
              ["--step", "sampleid_mapping", "--map-file", fix / "id_map.csv",
               "--meta-files", fix / "metadata_MIC.csv", "--output-dir", tmp_path])
    assert p.returncode == 0, p.stdout + p.stderr
    got = (tmp_path / "1_files_with_sampleid/metadata_MIC.csv").read_text()
    exp = (fix / "expected_metadata_MIC.csv").read_text()
    assert got == exp


def test_pseudobulk_qc(run_r, repo_root, tmp_path):
    fix = repo_root / FIX
    p = run_r(repo_root / WORKER,
              ["--step", "pseudobulk_qc", "--meta-files", fix / "metadata_MIC.csv",
               "--count-files", fix / "counts_MIC.csv.gz",
               "--tech-vars-file", fix / "tech_vars_MIC.csv", "--output-dir", tmp_path])
    assert p.returncode == 0, p.stdout + p.stderr
    d = tmp_path / "2_residuals/MIC"
    # filtered_raw_counts: version-independent -> byte exact
    assert (d / "MIC_filtered_raw_counts.txt").read_text() == \
        (fix / "expected_MIC_filtered_raw_counts.txt").read_text()
    # residuals: voom-derived -> tight numeric (labels/header exact)
    _assert_num_match((d / "MIC_residuals.txt").read_text(),
                      (fix / "expected_MIC_residuals.txt").read_text(), label_cols=1)


def test_phenotype_formatting(run_r, repo_root, tmp_path):
    fix = repo_root / FIX
    # ct = basename(dirname(residual_file)) -> place the ATAC residuals under MIC/
    ct_dir = tmp_path / "MIC"
    ct_dir.mkdir()
    (ct_dir / "atac_MIC_residuals.txt").write_text((fix / "atac_MIC_residuals.txt").read_text())
    p = run_r(repo_root / WORKER,
              ["--step", "phenotype_formatting",
               "--residual-files", ct_dir / "atac_MIC_residuals.txt", "--output-dir", tmp_path])
    assert p.returncode == 0, p.stdout + p.stderr
    out = tmp_path / "3_pheno_reformat/MIC_phenotype.bed.gz"
    assert (tmp_path / "3_pheno_reformat/MIC_phenotype.bed.gz.tbi").exists()
    got = gzip.open(out, "rt").read()
    exp = gzip.open(fix / "expected_MIC_phenotype.bed.gz", "rt").read()
    assert got == exp
