[workspace]
name = "xqtl-protocol"
channels = ["dnachun", "conda-forge", "bioconda"]
platforms = ["linux-64", "osx-arm64"]

[system-requirements]
libc = { family="glibc", version="2.17" }

[tasks]
test = "pytest tests"
test_scripts = "pytest tests/scripts"
test_notebooks = "pytest tests/notebooks"

[dependencies]
"r-argparser" = "*"
"r-corshrink" = "*"
"r-covr" = "*"
"r-jsonlite" = "*"
"r-ggnewscale" = "*"
"r-metafor" = "*"
"r-pkgdown" = "*"
"r-testthat" = "*"
"r-tidyverse" = "*"
"r-pecotmr" = "*"
"r-udr" = "*"
"pytest" = "*"
"pytest-cov" = "*"
"sos" = "*"
"python" = "3.12.*"
"setuptools" = "<81"
