[workspace]
name = "xqtl-protocol"
channels = ["dnachun", "conda-forge", "bioconda"]
platforms = [
    { platform = "linux-64", glibc = "2.17" },
    "osx-arm64"
]

[tasks]
test_scripts = "pytest tests/scripts -n auto --dist loadscope"
test_notebooks = "pytest tests/notebooks -n 2 --dist loadscope"
test = { depends-on = ["test_scripts", "test_notebooks"] }

[dependencies]
"pytest" = "*"
"pytest-cov" = "*"
"pytest-xdist" = "*"
"python" = "3.12.*"
"sos" = "*"
"setuptools" = "<81"
"coreutils" = "*"
"bioconductor-annotationhub" = "*"
"bioconductor-biomart" = "*"
"bioconductor-clusterprofiler" = "*"
"bioconductor-illuminahumanmethylation450kmanifest" = "*"
"bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19" = "*"
"bioconductor-impute" = "*"
"bioconductor-minfi" = "*"
"bioconductor-minfidata" = "*"
"bioconductor-pcatools" = "*"
"bioconductor-psichomics" = "*"
"bioconductor-sesame" = "*"
"bioconductor-sesamedata" = "*"
"bioconductor-singlecelltk" = "*"
"bioconductor-sva" = "*"
"bioconductor-txdbmaker" = "*"
"bioconductor-org.hs.eg.db" = "*"
"r-argparser" = "*"
"r-biocmanager" = "*"
"r-covr" = "*"
"r-testthat" = "*"
"r-tidyverse" = "*"
"r-base" = "*"
"r-catboost" = "*"
"r-jackstraw" = "*"
"r-jsonlite" = "*"
"r-ggnewscale" = "*"
"r-pecotmr" = "*"
"r-pkgdown" = "*"
"r-flashpcar" = "*"
"r-rmtstat" = "*"
"r-seurat" = "*"
"r-itertools" = "*"
"r-xgboost" = "*"
"apex" = "*"
"bcftools" = "*"
"bedtools" = "*"
"deeptools" = "*"
"fastp" = "*"
"fastqc" = "*"
"gcta" = "*"
"gffread" = "*"
"gzip" = "*"
"kent-tools" = "*"
"king" = "*"
"mofapy2" = "*"
"multiqc" = "*"
"picard" = "*"
"plink" = "*"
"plink2" = "*"
"polyfun" = "*"
"regtools" = "*"
"rnaseqc" = "*"
"rsem" = "*"
# "star" = "*"
"suppa" = "*"
"trimmomatic" = "*"
