[workspace]
name = "xqtl-protocol"
channels = ["dnachun", "conda-forge", "bioconda"]
platforms = ["linux-64", "osx-arm64"]

[system-requirements]
libc = { family="glibc", version="2.17" }

[tasks]
test = "pytest tests"
test_scripts = "pytest tests/scripts"
test_notebooks = "pytest tests/notebooks"

[dependencies]
"pytest" = "*"
"pytest-cov" = "*"
"python" = "3.12.*"
"sos" = "*"
"setuptools" = "<81"
"coreutils" = "*"
"bioconductor-annotationhub" = "*"
"bioconductor-biomart" = "*"
"bioconductor-clusterprofiler" = "*"
"bioconductor-illuminahumanmethylation450kmanifest" = "*"
"bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19" = "*"
"bioconductor-impute" = "*"
"bioconductor-minfi" = "*"
"bioconductor-minfidata" = "*"
"bioconductor-pcatools" = "*"
"bioconductor-psichomics" = "*"
"bioconductor-sesame" = "*"
"bioconductor-sesamedata" = "*"
"bioconductor-sva" = "*"
"bioconductor-txdbmaker" = "*"
"bioconductor-org.hs.eg.db" = "*"
"r-argparser" = "*"
"r-covr" = "*"
"r-testthat" = "*"
"r-tidyverse" = "*"
"r-base" = "*"
"r-catboost" = "*"
"r-jackstraw" = "*"
"r-jsonlite" = "*"
"r-ggnewscale" = "*"
"r-pecotmr" = "*"
"r-pkgdown" = "*"
"r-flashpcar" = "*"
"r-rmtstat" = "*"
"r-seurat" = "*"
"r-itertools" = "*"
"r-xgboost" = "*"
"apex" = "*"
"bedtools" = "*"
"deeptools" = "*"
"fastp" = "*"
"fastqc" = "*"
"gcta" = "*"
"gffread" = "*"
"gzip" = "*"
"king" = "*"
"mofapy2" = "*"
"multiqc" = "*"
"picard" = "*"
"regtools" = "*"
"rnaseqc" = "*"
"rsem" = "*"
# "star" = "*"
"trimmomatic" = "*"
