"""Notebook tier: splicing_calling.ipynb workers.

leafcutter_cluster_regtools.R is a faithful R port of leafcutter's
leafcutter_cluster_regtools.py (davidaknowles/leafcutter). The fixtures are real
regtools junctions for MWE SAMPLE_001/002 (chr22) and the byte-exact reference
outputs from the ORIGINAL Python (params -m 3 -l 500000 -p 0.001); the port must
reproduce all four outputs exactly.
"""
from __future__ import annotations

import gzip
import shutil

WORKER = "code/script/molecular_phenotypes/calling/leafcutter_cluster_regtools.R"
PSI_WORKER = "code/script/molecular_phenotypes/calling/splicing_calling.R"
RJ_WORKER = "code/script/molecular_phenotypes/calling/regtools_junctions.R"
FIX = "tests/fixtures/splicing_calling/leafcutter"
PSI_FIX = "tests/fixtures/splicing_calling/psichomics"
BAM = "tests/fixtures/phenotype_formatting/protocol_example.chr22_16M_17M.bam"


def _ungz(p):
    return gzip.open(p, "rt").read()


def test_leafcutter_cluster(run_r, repo_root, tmp_path):
    fix = repo_root / FIX
    jf = tmp_path / "juncfiles.txt"
    jf.write_text(f"{fix/'SAMPLE_001.junc.gz'}\n{fix/'SAMPLE_002.junc.gz'}\n")
    p = run_r(repo_root / WORKER,
              ["--juncfiles", jf, "--outprefix", "t", "--rundir", tmp_path,
               "--minclureads", 3, "--maxintronlen", 500000, "--mincluratio", 0.001])
    assert p.returncode == 0, p.stdout + p.stderr

    # plain-text intermediates must match byte-for-byte
    assert (tmp_path / "t_pooled").read_text() == (fix / "expected_pooled").read_text()
    assert (tmp_path / "t_refined").read_text() == (fix / "expected_refined").read_text()
    # gzipped count matrices compared decompressed (gzip bytes differ, content must not)
    assert _ungz(tmp_path / "t_perind.counts.gz") == _ungz(fix / "expected_perind.counts.gz")
    assert _ungz(tmp_path / "t_perind_numers.counts.gz") == _ungz(fix / "expected_perind_numers.counts.gz")


def test_regtools_junctions(run_r, repo_root, tmp_path):
    """regtools_junctions.R (pure-R/Bioconductor port of `regtools junctions extract`) must
    reproduce regtools BED12 output byte-for-byte. Reference generated by regtools 1.0.0 on the
    committed chr22:16M-17M bam (-a 8 -m 50 -M 500000 -s XS)."""
    import shutil
    bam = tmp_path / "s.bam"
    shutil.copy(repo_root / BAM, bam)                        # no index needed (sequential scan)
    out = tmp_path / "r.junc"
    p = run_r(repo_root / RJ_WORKER,
              ["--bam", bam, "--output", out, "--min-anchor", 8, "--min-intron", 50,
               "--max-intron", 500000, "--strandness", "XS"])
    assert p.returncode == 0, p.stdout + p.stderr
    assert out.read_text() == (repo_root / "tests/fixtures/splicing_calling/regtools"
                               / "expected_chr22_16M_17M.junc").read_text()


def test_junction_quant(run_r, repo_root, tmp_path):
    """psichomics_1: prepareJunctionQuant over STAR SJ.out.tab (SAMPLE_001/002, chr22) ->
    merged junction quantification table, compared to the committed reference."""
    for s in ("SAMPLE_001", "SAMPLE_002"):
        shutil.copy(repo_root / PSI_FIX / f"{s}.SJ.out.tab", tmp_path / f"{s}.SJ.out.tab")
    out = tmp_path / "psichomics_junctions.txt"
    p = run_r(repo_root / PSI_WORKER,
              ["--step", "junction_quant",
               "--inputs", tmp_path / "SAMPLE_001.SJ.out.tab", tmp_path / "SAMPLE_002.SJ.out.tab",
               "--output", out])
    assert p.returncode == 0, p.stdout + p.stderr
    assert out.read_text() == (repo_root / PSI_FIX / "expected_junctions.txt").read_text()



def test_quantify_psi(run_r, repo_root, tmp_path):
    """psichomics_2: quantifySplicing over a committed chr22 SUPPA annotation
    (built once via suppa.py generateEvents -> suppa_annot) and a junction table
    encoded in psichomics' junctionString format so events actually quantify.
    (Real STAR junctions use intron-boundary coords that need the production
    reference annotation; here we exercise the worker's read->quantify->write path.)"""
    fix = repo_root / PSI_FIX
    out = tmp_path / "psi_raw_data.tsv"
    p = run_r(repo_root / PSI_WORKER,
              ["--step", "quantify_psi",
               "--junctions", fix / "quantify_psi_junctions.txt",
               "--splicing-annotation", fix / "chr22_suppa_annotation.rds",
               "--output", out])
    assert p.returncode == 0, p.stdout + p.stderr
    lines = out.read_text().splitlines()
    assert lines[0].split("\t") == ["SAMPLE_001", "SAMPLE_002"]      # write.table: no rowname header
    events = [ln.split("\t")[0] for ln in lines[1:] if ln.strip()]
    assert events, "no PSI events quantified"
    assert all(e.split("_")[0] in {"SE", "MXE", "ALE", "AFE", "A3SS", "A5SS"} for e in events)
