"""Notebook tier: apa_calling.ipynb — DaPars2 ported to pure R (code/script/.../dapars.R),
removing python2 / bedtools / samtools / DaPars2.

References were generated by the SHIPPED DaPars2 python2 scripts adapted to python3
(system python3 has numpy): gtf2bed12 + DaPars_Extract_Anno (3'UTR extraction) + the
448-line Dapars2_Multi_Sample PDUI core. All steps are byte-identical to those references
(the PDUI core matches even at the degenerate coverage_threshold=0, via numpy-exact pairwise
summation). The bedtools `subtractBed` in extract_anno was cross-checked against a py3
reimplementation of its 0-based half-open semantics.
"""
from __future__ import annotations

import gzip

WORKER = "code/script/molecular_phenotypes/calling/dapars.R"
FIX = "tests/fixtures/apa_calling"


def _ungz(src, dst):
    dst.write_bytes(gzip.open(src, "rb").read())


def test_gtf2bed12(run_r, repo_root, tmp_path):
    gtf = tmp_path / "chr22.gtf"
    _ungz(repo_root / FIX / "chr22.hdr.gtf.gz", gtf)                 # has 5 header lines -> --skip-rows 5
    bed = tmp_path / "out.bed"; mp = tmp_path / "out.map"
    p = run_r(repo_root / WORKER, ["--step", "gtf2bed12", "--gtf", gtf, "--skip-rows", 5,
                                   "--out-bed", bed, "--out-map", mp])
    assert p.returncode == 0, p.stdout + p.stderr
    assert bed.read_text() == (repo_root / FIX / "expected_gene_annotation.bed").read_text()
    assert mp.read_text() == (repo_root / FIX / "expected_transcript_to_geneName.txt").read_text()


def test_extract_anno(run_r, repo_root, tmp_path):
    out = tmp_path / "3UTR.bed"
    p = run_r(repo_root / WORKER,
              ["--step", "extract_anno",
               "--bed", repo_root / FIX / "expected_gene_annotation.bed",
               "--symbol", repo_root / FIX / "expected_transcript_to_geneName.txt",
               "--output", out])
    assert p.returncode == 0, p.stdout + p.stderr
    assert out.read_text() == (repo_root / FIX / "expected_3UTR.bed").read_text()


def test_apa_main_pdui(run_r, repo_root, tmp_path):
    """The DaPars2 PDUI core: config -> wig coverage -> two-segment change-point -> PDUI,
    compared (data rows) to the py3 DaPars2 reference at coverage_threshold=1."""
    for s in ("SAMPLE_001", "SAMPLE_002"):
        _ungz(repo_root / FIX / f"{s}.wig.gz", tmp_path / f"{s}.wig")
    (tmp_path / "depth.txt").write_text((repo_root / FIX / "depth.txt").read_text())
    cfg = tmp_path / "config.txt"
    cfg.write_text("\n".join([
        f"Annotated_3UTR={repo_root / FIX / 'chr22_3UTR.bed'}",
        f"Aligned_Wig_files={tmp_path/'SAMPLE_001.wig'},{tmp_path/'SAMPLE_002.wig'}",
        f"Output_directory={tmp_path/'apa'}",
        "Output_result_file=Dapars2", "Coverage_threshold=1", "Num_Threads=1",
        f"sequencing_depth_file={tmp_path/'depth.txt'}"]) + "\n")
    p = run_r(repo_root / WORKER, ["--step", "apa_main", "--config", cfg, "--chr", "chr22"])
    assert p.returncode == 0, p.stdout + p.stderr
    out = tmp_path / "apa_chr22" / "Dapars2_result_temp.chr22.txt"
    data_rows = out.read_text().splitlines()[1:]                    # drop path-dependent header
    expected = (repo_root / FIX / "expected_pdui_data.txt").read_text().splitlines()
    assert data_rows == expected
